### ISSUE TITLE
Keep displaying which mode is selected: module or template

### ISSUE THREAD

**Issue by In1quity** [nyurik/dibabel-js#10]
When you select a mode, it gets darker, but when you click on the table, it returns to its original state.
![image](https://user-images.githubusercontent.com/22780294/90305490-12e65100-decc-11ea-9708-20d8b6b058b0.png)

**Comment by nyurik** [comment]
darker is an indicator of focus. Try hitting TAB.  There is no indicator of the toggle in filters in EUI in my understanding.

**Comment by In1quity** [comment]
Very strange, usually this behavior should be. To understand which filter is on.

**Comment by nyurik** [comment]
Actually EUI supports it -- see first demo on https://eui.elastic.co/#/forms/search-bar page (open/close buttons).  When clicked, the `<button>` element gets `euiFilterButton-hasActiveFilters` class. Since I used an icon instead of words, this class doesn't have much effect. Suggestions are welcome how we can change that class to highlight the icon.

**Comment by nyurik** [comment]
I changed it to a dropdown, now shows properly:

![image](https://user-images.githubusercontent.com/1641515/93154753-6f5aad00-f6d2-11ea-95c8-cc188aa0e1e5.png)
